# Generated by Django 5.2.8 on 2025-11-19 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produto_principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('INDISPONIVEL', 'Indisponível'), ('BAIXA_QUANTIDADE', 'Baixa Quantidade')], default='DISPONIVEL', max_length=50),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entrega_prevista', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.item')),
            ],
        ),
    ]
